### ISSUE TITLE
hello please help me

### ISSUE THREAD

**Issue by qcj1206** [SongRongLee/mir-svc#2]
I use python inference.py $src_file $target_dir $singer_id $model_path --pitch-shift $pitch_shift --two-phase --train-data-dir $train_data_dir to inference ADIZ 13.WAV convert singer JTAN. It neet 15hour on 2080Ti? Maybe is ture?

**Comment by jreoka** [comment]
Hmm it could. I'm also wondering how long it has to train before it saves a model checkpoint. Any ideas?

**Comment by SongRongLee** [comment]
Hi @qcj1206 @dillfrescott,
I've added a [section](https://github.com/SongRongLee/mir-svc#statistics) describing my hardware and training/inference time.
The checkpoints are saved every 10000 steps by default. The value is configurable.

**Comment by jreoka** [comment]
Im going on 2 hours 30 minutes on a colab gpu (I think its a Tesla T4) for a 26 second clip. Is this normal?

**Comment by jreoka** [comment]
Actually I suppose that's accurate considering it probably takes me about 6 or so minutes for a second of audio since its only 1 card.
